version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
        environment:
          TZ: '/usr/share/zoneinfo/Asia/Ho_Chi_Minh'

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/progress-bars

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run:
          name: Install global packages
          command: sudo yarn global add surge firebase-tools gatsby-cli

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run:
          name: Build
          command: |
            yarn build
            echo "Build Production..."
      - run:
          name: Deploy
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              firebase deploy --token=$FIREBASE_TOKEN
              echo "Deploying Hosting..."
            elif [[ $CIRCLE_BRANCH == "dev" ]]; then
              yarn surge 
              echo "Deploying Surge..."
            fi
