name: Progress Bars
on:
  push:
    branches:
      - master
      - cachee-ci
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install package
        run: yarn

      - name: Testing
        run: yarn test-ci

      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{secrets.GH_EMAIL}}
          git config --global user.name "tiendn"
          git remote set-url origin https://${{secrets.GH_TOKEN}}@github.com/tiendn/progress-bars.git
          npm run deploy
