name: Progress Bars
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cache node_modules
        id: cached-yarn
        uses: actions/cache@v1.0.3
        with:
          path: node_modules
          key: ${{ runner.os }}-progress-bars

      - name: Install package
        if: steps.cached-yarn.outputs.cache-hit != 'true'
        run: yarn

      # - name: Install package
      #   run: yarn

      - name: Testing
        run: yarn test-ci

      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{secrets.GH_EMAIL}}
          git config --global user.name "tiendn"
          git remote set-url origin https://${{secrets.GH_TOKEN}}@github.com/tiendn/progress-bars.git
          npm run deploy
